version: '3.8'


services:
  app:
    build: 
      context: ./vacci_track_backend
    restart: always
    image: vacci_track_docker_image
    container_name: vacci_track_docker_container
    env_file:
      - ./vacci_track_backend/django.env
    volumes:
      - ./vacci_track_backend:/vacci_track_backend
    depends_on:
      - postgres
    # ports:
    #   - 9000:9000
    # command: gunicorn --workers 3 --timeout 86400 --bind 0.0.0.0:8004 vacci_track_Website.wsgi:application
   

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: vacci_track_nginx_image
    container_name: vacci_track_nginx_container
    restart: always
    volumes:
      - ./vacci_track_backend/static:/vacci_track_backend/static
    env_file:
      - ./nginx/nginx.env
    ports:
      - 8010:8010
      - 8009:8009
    depends_on:
      - app

  postgres:
    build:
      context: ./postgresql
    image: vacci_track_postgresql_image
    container_name: vacci_track_postgresql_container
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./vacci_track_backend/django.env
    ports:
      - 5427:5432

  # # flutter_app:
  #   build: 
  #     context: ./vacci_track_frontend
  #     dockerfile: Dockerfile.flutter
  #   restart: always
  #   image: vacci_track_flutter_image
  #   container_name: vacci_track_flutter_container
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - ./vacci_track_frontend/flutter.env
  #   volumes:
  #     - ./vacci_track_frontend/:/vtf_app/