# Generated by Django 4.2.2 on 2023-08-17 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('dose_number', models.PositiveIntegerField(db_index=True)),
                ('gap_before_next_dose', models.PositiveIntegerField(db_index=True, help_text='Gap Before Next Dose is Due. In Months ')),
                ('detail', models.TextField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, db_index=True, null=True)),
                ('pr_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email_id', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('eligibility', models.CharField(choices=[('Eligible', 'Eligible'), ('Non - Eligible', 'Non - Eligible')], db_index=True, max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes_remarks', models.TextField(blank=True, db_index=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='vacci_track_backend_app.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='vacci_track_backend_app.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('facility_id', models.CharField(db_index=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('total_number_of_doses', models.PositiveIntegerField(db_index=True)),
                ('other_notes', models.TextField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_date', models.DateField(db_index=True)),
                ('dose_administered_by_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('dose_administered_by_pr_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('next_dose_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes_remarks', models.TextField(blank=True, db_index=True, null=True)),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccination', to='vacci_track_backend_app.dose')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccinations', to='vacci_track_backend_app.employee')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccination', to='vacci_track_backend_app.vaccination')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='vacci_track_backend_app.facility'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='vacci_track_backend_app.vaccination'),
        ),
        migrations.AddField(
            model_name='dose',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose', to='vacci_track_backend_app.vaccination'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='vacci_track_backend_app.employee'),
        ),
    ]
