# Generated by Django 4.2.6 on 2023-10-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uhid',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
