# Generated by Django 4.2.2 on 2023-08-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, db_index=True, to='vacci_track_backend_app.vaccination'),
        ),
    ]
