# Generated by Django 4.2.2 on 2023-06-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevaccination',
            name='dose_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeevaccination',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccinations', to='vacci_track_backend_app.employee'),
        ),
    ]
