# Generated by Django 4.2.2 on 2023-06-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacci_track_backend_app', '0002_alter_employeevaccination_dose_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='vacci_track_backend_app.employee'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose', to='vacci_track_backend_app.vaccination'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='vacci_track_backend_app.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='vacci_track_backend_app.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='vacci_track_backend_app.facility'),
        ),
        migrations.AlterField(
            model_name='employeevaccination',
            name='dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccination', to='vacci_track_backend_app.dose'),
        ),
    ]
