# Generated by Django 4.2.7 on 2023-11-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='long', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
