# Generated by Django 4.2.2 on 2023-08-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0002_alter_employee_vaccinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevaccination',
            name='is_dose_due',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
