# Generated by Django 4.2.2 on 2023-07-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0003_alter_department_department_hod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
