# Generated by Django 4.2.2 on 2023-08-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0003_employeevaccination_is_dose_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevaccination',
            name='is_dose_due',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is This Dose Due?'),
        ),
    ]
