# Generated by Django 4.2.7 on 2023-11-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0005_alter_appuser_pr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevaccination',
            name='dose_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
