# Generated by Django 4.2.2 on 2023-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0006_rename_eligibilty_employee_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
