# Generated by Django 4.2.2 on 2023-08-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0007_alter_employee_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email_address',
            new_name='email_id',
        ),
    ]
