# Generated by Django 4.2.7 on 2023-11-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0007_alter_employeevaccination_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevaccination',
            name='dose_date',
            field=models.DateField(db_index=True),
        ),
    ]
