# Generated by Django 4.2.7 on 2023-11-29 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0008_alter_employeevaccination_dose_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_date', models.DateField(db_index=True)),
                ('dose_administered_by_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('dose_administered_by_pr_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('next_dose_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_dose_due', models.BooleanField(db_index=True, default=False, verbose_name='Is This Dose Due?')),
                ('notes_remarks', models.TextField(blank=True, db_index=True, null=True)),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccination', to='vacci_track_backend_app.dose')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccinations', to='vacci_track_backend_app.employee')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_vaccination', to='vacci_track_backend_app.vaccination')),
            ],
            options={
                'unique_together': {('employee', 'vaccination', 'dose')},
            },
        ),
        migrations.DeleteModel(
            name='EmployeeVaccination',
        ),
    ]
