# Generated by Django 4.2.7 on 2023-11-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0009_employeevaccinationrecord_delete_employeevaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevaccinationrecord',
            name='dose_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
