# Generated by Django 4.2.7 on 2023-12-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0012_alter_employee_vaccinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevaccinationrecord',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is This Dose Due?'),
        ),
    ]
