# Generated by Django 4.2.7 on 2023-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0013_employeevaccinationrecord_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeevaccinationrecord',
            name='next_dose_due_date',
        ),
        migrations.AddField(
            model_name='employeevaccinationrecord',
            name='dose_due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Dose Due Date'),
        ),
        migrations.AlterField(
            model_name='employeevaccinationrecord',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is All The Dose Completed?'),
        ),
    ]
