# Generated by Django 5.0.1 on 2024-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacci_track_backend_app', '0016_alter_employeevaccinationrecord_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('Eligible', 'Eligible'), ('Non - Eligible', 'Non - Eligible')], db_index=True, max_length=20, null=True),
        ),
    ]
